export const BlockNames = {
    pixelate: "PixelateBlock",
    blackAndWhite: "BlackAndWhiteBlock",
    exposure: "ExposureBlock",
    contrast: "ContrastBlock",
    desaturate: "DesaturateBlock",
    posterize: "PosterizeBlock",
    kaleidoscope: "KaleidoscopeBlock",
    greenScreen: "GreenScreenBlock",
    glass: "GlassBlock",
    frame: "FrameBlock",
    blur: "BlurBlock",
    directionalBlur: "DirectionalBlurBlock",
    composition: "CompositionBlock",
    blackAndWhiteAndBlur: "BlackAndWhiteAndBlurBlock",
    glitch: "GlitchBlock",
    tile: "TileBlock",
    wipe: "WipeBlock",
    mask: "MaskBlock",
    starryPlanes: "StarryPlanesBlock",
    tunnel: "TunnelBlock",
    fireworks: "FireworksBlock",
    aurora: "AuroraBlock",
    vhsGlitch: "vhsGlitchBlock",
    softThreshold: "SoftThresholdBlock",
    sketch: "SketchBlock",
};
