/* eslint-disable @typescript-eslint/naming-convention */

export const blockTooltips: { [key: string]: string } = {
    Float: "A floating point number representing a value with a fractional component",
    Texture: "A node for reading a linked or embedded texture file",
    CopyBlock: "Copy the input texture to the output texture",
    OutputBlock: "Final output of the Smart Filter, this represents the canvas or an offscreen texture",
    GlitchBlock: "Funky glitch transition",
    TileBlock: "Transition from one texture to another using tiles",
    WipeBlock: "Transition from one texture to another using a wipe",
    BlackAndWhiteBlock: "Transform the input texture to black and white",
    BlurBlock: "Blur the input texture",
    BlackAndWhiteAndBlurBlock: "Transforms the input texture to black and white and blurs it",
    CompositionBlock: "Composite the foreground texture over the background texture",
    FrameBlock: "Green screen like effect",
    GlassBlock: "Creates a glass like effect",
    KaleidoscopeBlock: "Kaleidoscope effect",
    InputBlock: "Adds inputs to the Smart Filter",
    PixelateBlock: "Add pixelation to the input texture",
    PosterizeBlock: "Posterize to the input texture",
    ContrastBlock: "Change the contrast of the input texture",
    GreenScreenBlock: "Help replacing a green screen background with a different texture",
};

export const allBlockNames: { [key: string]: string[] } = {
    // Custom_Frames: customFrameNames,
    // Custom_Blocks: customBlockNames,
    Inputs: ["Float", "Color3", "Texture", "WebCam"],
    Transitions: ["GlitchBlock", "TileBlock", "WipeBlock"],
    Effects: [
        "CopyBlock",
        "BlackAndWhiteBlock",
        "BlurBlock",
        "CompositionBlock",
        "FrameBlock",
        "GlassBlock",
        "KaleidoscopeBlock",
        "PixelateBlock",
        "PosterizeBlock",
        "DesaturateBlock",
        "ContrastBlock",
        "GreenScreenBlock",
        "BlackAndWhiteAndBlurBlock",
    ],
};
