export const BlockNames = {
    webCam: "WebCamInputBlock",
    time: "TimeBlock",
    pixelate: "PixelateBlock",
    blackAndWhite: "BlackAndWhiteBlock",
    exposure: "ExposureBlock",
    contrast: "ContrastBlock",
    desaturate: "DesaturateBlock",
    posterize: "PosterizeBlock",
    kaleidoscope: "KaleidoscopeBlock",
    greenScreen: "GreenScreenBlock",
    glass: "GlassBlock",
    frame: "FrameBlock",
    blur: "BlurBlock",
    directionalBlur: "DirectionalBlurBlock",
    composition: "CompositionBlock",
    glitch: "GlitchBlock",
    tile: "TileBlock",
    wipe: "WipeBlock",
    mask: "MaskBlock",
    particle: "ParticleBlock",
    spritesheet: "SpritesheetBlock",
    tint: "TintBlock",
    premultiplyAlpha: "PremultiplyAlphaBlock",
};
